export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const CATEGORY_DETAILS_REQUEST = "CATEGORY_DETAILS_REQUEST";
export const CATEGORY_DETAILS_SUCCESS = "CATEGORY_DETAILS_SUCCESS";
export const CATEGORY_DETAILS_FAIL = "CATEGORY_DETAILS_FAIL";

export const CATEGORY_ADD_REQUEST = "CATEGORY_ADD_REQUEST";
export const CATEGORY_ADD_SUCCESS = "CATEGORY_ADD_SUCCESS";
export const CATEGORY_ADD_FAIL = "CATEGORY_ADD_FAIL";

export const SUBCATEGORY_ADD_REQUEST = "SUBCATEGORY_ADD_REQUEST";
export const SUBCATEGORY_ADD_SUCCESS = "SUBCATEGORY_ADD_SUCCESS";
export const SUBCATEGORY_ADD_FAIL = "SUBCATEGORY_ADD_FAIL";

export const EDIT_UPDATE_REQUEST = "EDIT_UPDATE_REQUEST";
export const EDIT_UPDATE_SUCCESS = "EDIT_UPDATE_SUCCESS";
export const EDIT_UPDATE_FAIL = "EDIT_UPDATE_FAIL";

export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_FAIL";

export const SUBCATEGORY_DELETE_REQUEST = "SUBCATEGORY_DELETE_REQUEST";
export const SUBCATEGORY_DELETE_SUCCESS = "SUBCATEGORY_DELETE_SUCCESS";
export const SUBCATEGORY_DELETE_FAIL = "SUBCATEGORY_DELETE_FAIL";

export const PROBLEM_ADD_REQUEST = "PROBLEM_ADD_REQUEST";
export const PROBLEM_ADD_SUCCESS = "PROBLEM_ADD_SUCCESS";
export const PROBLEM_ADD_FAIL = "PROBLEM_ADD_FAIL";

export const PROBLEM_DELETE_REQUEST = "PROBLEM_DELETE_REQUEST";
export const PROBLEM_DELETE_SUCCESS = "PROBLEM_DELETE_SUCCESS";
export const PROBLEM_DELETE_FAIL = "PROBLEM_DELETE_FAIL";

export const EDIT_NOTE_REQUEST = "EDIT_NOTE_REQUEST";
export const EDIT_NOTE_SUCCESS = "EDIT_NOTE_SUCCESS";
export const EDIT_NOTE_FAIL = "EDIT_NOTE_FAIL";
